# except Excetion as e에서 e가 예외 발생 내용이 담김
try:
    print(param)
except Exception as e:
    print(e) #name 'param' is not defined 출력